# Caminho para a raiz do conjunto de dados
path: ./dataset

# Caminhos relativos para imagens de treino e validação
train: images/train
val: images/train  # por enquanto, usamos o mesmo conjunto para treino e validação

# Classes do dataset
names:
  0: gado
